// This file has been generated by the dart_json_mapper package.
// https://github.com/k-paxian/dart-json-mapper
import 'authentication_model.dart';
import 'package:dart_json_mapper/dart_json_mapper.dart' show JsonMapper, JsonMapperAdapter, typeOf;

// No output from reflectable, there is no `main`.
final authentication_modelAdapter = JsonMapperAdapter(
  title: 'authentication_modelAdapter',
  url: 'asset:flutter_model_form_validation/example/lib/entities/authentication_model.dart',
  valueDecorators: {
    typeOf<List<AuthenticationModel>>(): (value) => value.cast<AuthenticationModel>(),
    typeOf<Set<AuthenticationModel>>(): (value) => value.cast<AuthenticationModel>()
});

JsonMapper initializeJsonMapper({Iterable<JsonMapperAdapter> adapters = const []}) {
  _initializeReflectable();
  [...adapters, authentication_modelAdapter].forEach((x) => JsonMapper().useAdapter(x));
  return JsonMapper();
}