targets:
  $default:
    builders:
      dart_json_mapper:
        generate_for:
          - lib/entities/authentication_model.dart
      reflectable:
        generate_for:
          - lib/main.dart
        options:
          formatted: true