// This file has been generated by the dart_json_mapper package.
// https://github.com/k-paxian/dart-json-mapper
import 'package:dart_json_mapper/dart_json_mapper.dart' show JsonMapper, JsonMapperAdapter, typeOf;

// No output from reflectable, there is no `main`.
final login_formAdapter = JsonMapperAdapter(
  title: 'login_formAdapter',
  url: 'asset:flutter_model_form_validation/example/lib/login_form.dart',
  valueDecorators: {

});

JsonMapper initializeJsonMapper({Iterable<JsonMapperAdapter> adapters = const []}) {
  _initializeReflectable();
  [...adapters, login_formAdapter].forEach((x) => JsonMapper().useAdapter(x));
  return JsonMapper();
}