// This file has been generated by the dart_json_mapper package.
// https://github.com/k-paxian/dart-json-mapper
import 'package:dart_json_mapper/dart_json_mapper.dart' show JsonMapper, JsonMapperAdapter, typeOf;

// No output from reflectable, there is no `main`.
final main_reflectableAdapter = JsonMapperAdapter(
  title: 'main_reflectableAdapter',
  url: 'asset:flutter_model_form_validation/example/lib/main.reflectable.dart',
  valueDecorators: {

});

JsonMapper initializeJsonMapper({Iterable<JsonMapperAdapter> adapters = const []}) {
  _initializeReflectable();
  [...adapters, main_reflectableAdapter].forEach((x) => JsonMapper().useAdapter(x));
  return JsonMapper();
}