// This file has been generated by the reflectable package.
// https://github.com/dart-lang/reflectable.

import 'dart:core';
import 'package:dart_json_mapper/src/model/annotations.dart' as prefix2;
import 'package:example/entities/authentication_model.dart' as prefix1;
import 'package:flutter_model_form_validation/src/annotations/flutter_model_form_validator.dart'
    as prefix0;
import 'package:flutter_model_form_validation/src/annotations/validators/email.dart'
    as prefix4;
import 'package:flutter_model_form_validation/src/annotations/validators/membership_password.dart'
    as prefix5;
import 'package:flutter_model_form_validation/src/annotations/validators/required.dart'
    as prefix3;

// ignore_for_file: prefer_adjacent_string_concatenation
// ignore_for_file: prefer_collection_literals
// ignore_for_file: unnecessary_const
// ignore_for_file: implementation_imports

// ignore:unused_import
import 'package:reflectable/mirrors.dart' as m;
// ignore:unused_import
import 'package:reflectable/src/reflectable_builder_based.dart' as r;
// ignore:unused_import
import 'package:reflectable/reflectable.dart' as r show Reflectable;

final _data = <r.Reflectable, r.ReflectorData>{
  const prefix0.FlutterModelFormValidator(): r.ReflectorData(
      <m.TypeMirror>[
        r.NonGenericClassMirrorImpl(
            r'AuthenticationModel',
            r'.AuthenticationModel',
            7,
            0,
            const prefix0.FlutterModelFormValidator(),
            const <int>[0, 1],
            const <int>[6, 7, 8, 9, 10, 2, 3, 4, 5],
            const <int>[],
            -1,
            {},
            {},
            {},
            -1,
            -1,
            const <int>[-1],
            const <Object>[
              prefix0.flutterModelFormValidator,
              prefix2.jsonSerializable
            ],
            null)
      ],
      <m.DeclarationMirror>[
        r.VariableMirrorImpl(
            r'email',
            32773,
            0,
            const prefix0.FlutterModelFormValidator(),
            -1,
            -1,
            -1,
            null, const <Object>[
          const prefix3.Required(error: 'Email is required'),
          const prefix4.Email(error: 'Invalid email')
        ]),
        r.VariableMirrorImpl(
            r'password',
            32773,
            0,
            const prefix0.FlutterModelFormValidator(),
            -1,
            -1,
            -1,
            null, const <Object>[
          const prefix3.Required(error: 'Password is required'),
          const prefix5.MembershipPassword(
              minLength: 8,
              maxLength: 16,
              includesAlphabeticalCharacters: true,
              includesUppercaseCharacters: true,
              includesNumericalCharacters: true,
              includesSpecialCharacters: true,
              error: 'Invalid password')
        ]),
        r.ImplicitGetterMirrorImpl(
            const prefix0.FlutterModelFormValidator(), 0, 2),
        r.ImplicitSetterMirrorImpl(
            const prefix0.FlutterModelFormValidator(), 0, 3),
        r.ImplicitGetterMirrorImpl(
            const prefix0.FlutterModelFormValidator(), 1, 4),
        r.ImplicitSetterMirrorImpl(
            const prefix0.FlutterModelFormValidator(), 1, 5),
        r.MethodMirrorImpl(
            r'==',
            131074,
            null,
            -1,
            -1,
            -1,
            null,
            const <int>[2],
            const prefix0.FlutterModelFormValidator(),
            const []),
        r.MethodMirrorImpl(r'toString', 131074, null, -1, -1, -1, null,
            const <int>[], const prefix0.FlutterModelFormValidator(), const []),
        r.MethodMirrorImpl(
            r'noSuchMethod',
            65538,
            null,
            null,
            -1,
            -1,
            null,
            const <int>[3],
            const prefix0.FlutterModelFormValidator(),
            const []),
        r.MethodMirrorImpl(r'hashCode', 131075, null, -1, -1, -1, null,
            const <int>[], const prefix0.FlutterModelFormValidator(), const []),
        r.MethodMirrorImpl(r'runtimeType', 131075, null, -1, -1, -1, null,
            const <int>[], const prefix0.FlutterModelFormValidator(), const [])
      ],
      <m.ParameterMirror>[
        r.ParameterMirrorImpl(
            r'_email',
            32870,
            3,
            const prefix0.FlutterModelFormValidator(),
            -1,
            -1,
            -1,
            null,
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'_password',
            32870,
            5,
            const prefix0.FlutterModelFormValidator(),
            -1,
            -1,
            -1,
            null,
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'other',
            32774,
            6,
            const prefix0.FlutterModelFormValidator(),
            -1,
            -1,
            -1,
            null,
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'invocation',
            32774,
            8,
            const prefix0.FlutterModelFormValidator(),
            -1,
            -1,
            -1,
            null,
            const [],
            null,
            null)
      ],
      <Type>[prefix1.AuthenticationModel],
      1,
      {
        r'==': (dynamic instance) => (x) => instance == x,
        r'toString': (dynamic instance) => instance.toString,
        r'noSuchMethod': (dynamic instance) => instance.noSuchMethod,
        r'hashCode': (dynamic instance) => instance.hashCode,
        r'runtimeType': (dynamic instance) => instance.runtimeType,
        r'email': (dynamic instance) => instance.email,
        r'password': (dynamic instance) => instance.password
      },
      {
        r'email=': (dynamic instance, value) => instance.email = value,
        r'password=': (dynamic instance, value) => instance.password = value
      },
      null,
      []),
  const prefix2.JsonSerializable(): r.ReflectorData(
      <m.TypeMirror>[
        r.NonGenericClassMirrorImpl(
            r'AuthenticationModel',
            r'.AuthenticationModel',
            7,
            0,
            const prefix2.JsonSerializable(),
            const <int>[0, 1, 6],
            const <int>[7, 8, 9, 10, 11, 2, 3, 4, 5],
            const <int>[],
            -1,
            {},
            {},
            {
              r'': (b) => ({email, password}) => b
                  ? prefix1.AuthenticationModel(
                      email: email, password: password)
                  : null
            },
            -1,
            0,
            const <int>[],
            const <Object>[
              prefix0.flutterModelFormValidator,
              prefix2.jsonSerializable
            ],
            null)
      ],
      <m.DeclarationMirror>[
        r.VariableMirrorImpl(
            r'email',
            32773,
            0,
            const prefix2.JsonSerializable(),
            -1,
            1,
            1, const <int>[], const <Object>[
          const prefix3.Required(error: 'Email is required'),
          const prefix4.Email(error: 'Invalid email')
        ]),
        r.VariableMirrorImpl(
            r'password',
            32773,
            0,
            const prefix2.JsonSerializable(),
            -1,
            1,
            1, const <int>[], const <Object>[
          const prefix3.Required(error: 'Password is required'),
          const prefix5.MembershipPassword(
              minLength: 8,
              maxLength: 16,
              includesAlphabeticalCharacters: true,
              includesUppercaseCharacters: true,
              includesNumericalCharacters: true,
              includesSpecialCharacters: true,
              error: 'Invalid password')
        ]),
        r.ImplicitGetterMirrorImpl(const prefix2.JsonSerializable(), 0, 2),
        r.ImplicitSetterMirrorImpl(const prefix2.JsonSerializable(), 0, 3),
        r.ImplicitGetterMirrorImpl(const prefix2.JsonSerializable(), 1, 4),
        r.ImplicitSetterMirrorImpl(const prefix2.JsonSerializable(), 1, 5),
        r.MethodMirrorImpl(r'', 0, 0, -1, 0, 0, const <int>[],
            const <int>[0, 1], const prefix2.JsonSerializable(), const []),
        r.MethodMirrorImpl(r'==', 131074, null, -1, 2, 2, const <int>[],
            const <int>[4], const prefix2.JsonSerializable(), const []),
        r.MethodMirrorImpl(r'toString', 131074, null, -1, 1, 1, const <int>[],
            const <int>[], const prefix2.JsonSerializable(), const []),
        r.MethodMirrorImpl(
            r'noSuchMethod',
            65538,
            null,
            null,
            null,
            null,
            const <int>[],
            const <int>[5],
            const prefix2.JsonSerializable(),
            const []),
        r.MethodMirrorImpl(r'hashCode', 131075, null, -1, 3, 3, const <int>[],
            const <int>[], const prefix2.JsonSerializable(), const []),
        r.MethodMirrorImpl(
            r'runtimeType',
            131075,
            null,
            -1,
            4,
            4,
            const <int>[],
            const <int>[],
            const prefix2.JsonSerializable(),
            const [])
      ],
      <m.ParameterMirror>[
        r.ParameterMirrorImpl(
            r'email',
            45062,
            6,
            const prefix2.JsonSerializable(),
            -1,
            1,
            1,
            const <int>[],
            const [],
            null,
            #email),
        r.ParameterMirrorImpl(
            r'password',
            45062,
            6,
            const prefix2.JsonSerializable(),
            -1,
            1,
            1,
            const <int>[],
            const [],
            null,
            #password),
        r.ParameterMirrorImpl(
            r'_email',
            32870,
            3,
            const prefix2.JsonSerializable(),
            -1,
            1,
            1,
            const <int>[],
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'_password',
            32870,
            5,
            const prefix2.JsonSerializable(),
            -1,
            1,
            1,
            const <int>[],
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'other',
            32774,
            7,
            const prefix2.JsonSerializable(),
            -1,
            5,
            5,
            const <int>[],
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'invocation',
            32774,
            9,
            const prefix2.JsonSerializable(),
            -1,
            6,
            6,
            const <int>[],
            const [],
            null,
            null)
      ],
      <Type>[
        prefix1.AuthenticationModel,
        String,
        bool,
        int,
        Type,
        Object,
        Invocation
      ],
      1,
      {
        r'==': (dynamic instance) => (x) => instance == x,
        r'toString': (dynamic instance) => instance.toString,
        r'noSuchMethod': (dynamic instance) => instance.noSuchMethod,
        r'hashCode': (dynamic instance) => instance.hashCode,
        r'runtimeType': (dynamic instance) => instance.runtimeType,
        r'email': (dynamic instance) => instance.email,
        r'password': (dynamic instance) => instance.password
      },
      {
        r'email=': (dynamic instance, value) => instance.email = value,
        r'password=': (dynamic instance, value) => instance.password = value
      },
      null,
      [])
};

final _memberSymbolMap = null;

void initializeReflectable() {
  r.data = _data;
  r.memberSymbolMap = _memberSymbolMap;
}
