// This file has been generated by the reflectable package.
// https://github.com/dart-lang/reflectable.

import 'dart:core';
import 'models.dart' as prefix1;
import 'package:flutter_model_form_validation/src/annotations/flutter_model_form_validator.dart'
    as prefix0;
import 'package:flutter_model_form_validation/src/annotations/validators/greater_than.dart'
    as prefix5;
import 'package:flutter_model_form_validation/src/annotations/validators/nb_items.dart'
    as prefix2;
import 'package:flutter_model_form_validation/src/annotations/validators/required.dart'
    as prefix3;
import 'package:flutter_model_form_validation/src/annotations/validators/string_length.dart'
    as prefix4;
import 'package:flutter_model_form_validation/src/form_builder/form_declarers/form_array_element.dart'
    as prefix7;
import 'package:flutter_model_form_validation/src/form_builder/form_declarers/form_control_element.dart'
    as prefix8;
import 'package:flutter_model_form_validation/src/form_builder/form_declarers/form_group_element.dart'
    as prefix6;

// ignore_for_file: prefer_adjacent_string_concatenation
// ignore_for_file: prefer_collection_literals
// ignore_for_file: unnecessary_const
// ignore_for_file: implementation_imports

// ignore:unused_import
import 'package:reflectable/mirrors.dart' as m;
// ignore:unused_import
import 'package:reflectable/src/reflectable_builder_based.dart' as r;
// ignore:unused_import
import 'package:reflectable/reflectable.dart' as r show Reflectable;

final _data = <r.Reflectable, r.ReflectorData>{
  const prefix0.FlutterModelFormValidator(): r.ReflectorData(
      <m.TypeMirror>[
        r.NonGenericClassMirrorImpl(
            r'StepForm',
            r'example.models.StepForm',
            7,
            0,
            const prefix0.FlutterModelFormValidator(),
            const <int>[0, 1],
            const <int>[17, 18, 19, 20, 21, 22, 13, 14, 15, 16],
            const <int>[],
            -1,
            {},
            {},
            {},
            0,
            -1,
            const <int>[-1],
            const <Object>[prefix0.flutterModelFormValidator],
            null),
        r.NonGenericClassMirrorImpl(
            r'Reader',
            r'example.models.Reader',
            7,
            1,
            const prefix0.FlutterModelFormValidator(),
            const <int>[2, 3, 4, 5, 6],
            const <int>[
              17,
              18,
              19,
              20,
              21,
              22,
              23,
              24,
              25,
              26,
              27,
              28,
              29,
              30,
              31,
              32
            ],
            const <int>[],
            -1,
            {},
            {},
            {},
            0,
            -1,
            const <int>[-1],
            const <Object>[prefix0.flutterModelFormValidator],
            null),
        r.NonGenericClassMirrorImpl(
            r'Book',
            r'example.models.Book',
            7,
            2,
            const prefix0.FlutterModelFormValidator(),
            const <int>[7, 8, 9, 10],
            const <int>[17, 18, 19, 20, 21, 22, 33, 34, 35, 36, 37, 38, 39, 40],
            const <int>[],
            -1,
            {},
            {},
            {},
            0,
            -1,
            const <int>[-1],
            const <Object>[prefix0.flutterModelFormValidator],
            null),
        r.NonGenericClassMirrorImpl(
            r'EGender',
            r'example.models.EGender',
            524295,
            3,
            const prefix0.FlutterModelFormValidator(),
            const <int>[41],
            const <int>[17, 41, 19, 20, 21, 42],
            const <int>[],
            -1,
            {},
            {},
            {},
            0,
            -1,
            const <int>[-1],
            const <Object>[prefix0.flutterModelFormValidator],
            null),
        r.NonGenericClassMirrorImpl(
            r'ELiteraryGenre',
            r'example.models.ELiteraryGenre',
            524295,
            4,
            const prefix0.FlutterModelFormValidator(),
            const <int>[43],
            const <int>[17, 43, 19, 20, 21, 44],
            const <int>[],
            -1,
            {},
            {},
            {},
            0,
            -1,
            const <int>[-1],
            const <Object>[prefix0.flutterModelFormValidator],
            null)
      ],
      <m.DeclarationMirror>[
        r.VariableMirrorImpl(
            r'reader',
            2129925,
            0,
            const prefix0.FlutterModelFormValidator(),
            -1,
            5,
            6,
            null, const []),
        r.VariableMirrorImpl(
            r'books',
            2129925,
            0,
            const prefix0.FlutterModelFormValidator(),
            -1,
            7,
            8,
            null, const <Object>[
          const prefix2.NbItems(
              min: '1', error: 'reader must have at least one book')
        ]),
        r.VariableMirrorImpl(
            r'firstName',
            2129925,
            1,
            const prefix0.FlutterModelFormValidator(),
            -1,
            9,
            10,
            null, const <Object>[
          const prefix3.Required(error: 'firstname is required'),
          const prefix4.StringLength(
              min: 3,
              max: 50,
              error: 'firstname must have between 3 and 50 characters')
        ]),
        r.VariableMirrorImpl(
            r'lastName',
            2129925,
            1,
            const prefix0.FlutterModelFormValidator(),
            -1,
            9,
            10,
            null, const <Object>[
          const prefix3.Required(error: 'lastname is required'),
          const prefix4.StringLength(
              min: 3,
              max: 50,
              error: 'lastname must have between 3 and 50 characters')
        ]),
        r.VariableMirrorImpl(
            r'gender',
            2129925,
            1,
            const prefix0.FlutterModelFormValidator(),
            -1,
            11,
            12,
            null, const <Object>[
          const prefix3.Required(error: 'gender is required')
        ]),
        r.VariableMirrorImpl(
            r'birthDay',
            2129925,
            1,
            const prefix0.FlutterModelFormValidator(),
            -1,
            13,
            14,
            null, const <Object>[
          const prefix3.Required(error: 'birthday is required')
        ]),
        r.VariableMirrorImpl(
            r'subscriptionDate',
            2129925,
            1,
            const prefix0.FlutterModelFormValidator(),
            -1,
            13,
            14,
            null, const <Object>[
          const prefix3.Required(error: 'subscriptionDate is required'),
          const prefix5.GreaterThan(
              valueToCompareOnProperty: 'birthDay',
              error: 'subscription date must be greater than birthday')
        ]),
        r.VariableMirrorImpl(
            r'title',
            2129925,
            2,
            const prefix0.FlutterModelFormValidator(),
            -1,
            9,
            10,
            null, const <Object>[
          const prefix3.Required(error: 'title is required'),
          const prefix4.StringLength(
              min: 3,
              max: 100,
              error: 'title must have between 3 and 100 characters')
        ]),
        r.VariableMirrorImpl(
            r'literaryGenres',
            2129925,
            2,
            const prefix0.FlutterModelFormValidator(),
            -1,
            15,
            16,
            null, const <Object>[
          const prefix3.Required(error: 'literaty genre is required')
        ]),
        r.VariableMirrorImpl(
            r'releaseDate',
            2129925,
            2,
            const prefix0.FlutterModelFormValidator(),
            -1,
            13,
            14,
            null, const <Object>[
          const prefix3.Required(error: 'release date is required')
        ]),
        r.VariableMirrorImpl(
            r'price',
            2129925,
            2,
            const prefix0.FlutterModelFormValidator(),
            -1,
            17,
            18,
            null, const <Object>[
          const prefix3.Required(error: 'price is required'),
          const prefix5.GreaterThan(
              valueToCompare: '0', error: 'price must be greater than 0')
        ]),
        r.VariableMirrorImpl(
            r'index',
            33861,
            3,
            const prefix0.FlutterModelFormValidator(),
            -1,
            19,
            19,
            null, const []),
        r.VariableMirrorImpl(
            r'index',
            33861,
            4,
            const prefix0.FlutterModelFormValidator(),
            -1,
            19,
            19,
            null, const []),
        r.ImplicitGetterMirrorImpl(
            const prefix0.FlutterModelFormValidator(), 0, 13),
        r.ImplicitSetterMirrorImpl(
            const prefix0.FlutterModelFormValidator(), 0, 14),
        r.ImplicitGetterMirrorImpl(
            const prefix0.FlutterModelFormValidator(), 1, 15),
        r.ImplicitSetterMirrorImpl(
            const prefix0.FlutterModelFormValidator(), 1, 16),
        r.MethodMirrorImpl(
            r'==',
            131074,
            null,
            -1,
            20,
            20,
            null,
            const <int>[2],
            const prefix0.FlutterModelFormValidator(),
            const []),
        r.MethodMirrorImpl(r'toString', 131074, null, -1, 21, 21, null,
            const <int>[], const prefix0.FlutterModelFormValidator(), const []),
        r.MethodMirrorImpl(
            r'noSuchMethod',
            65538,
            null,
            null,
            null,
            null,
            null,
            const <int>[3],
            const prefix0.FlutterModelFormValidator(),
            const []),
        r.MethodMirrorImpl(r'hashCode', 131075, null, -1, 19, 19, null,
            const <int>[], const prefix0.FlutterModelFormValidator(), const []),
        r.MethodMirrorImpl(r'runtimeType', 131075, null, -1, 22, 22, null,
            const <int>[], const prefix0.FlutterModelFormValidator(), const []),
        r.MethodMirrorImpl(
            r'getPropertyFullname',
            131074,
            null,
            -1,
            21,
            21,
            null,
            const <int>[4],
            const prefix0.FlutterModelFormValidator(),
            const []),
        r.ImplicitGetterMirrorImpl(
            const prefix0.FlutterModelFormValidator(), 2, 23),
        r.ImplicitSetterMirrorImpl(
            const prefix0.FlutterModelFormValidator(), 2, 24),
        r.ImplicitGetterMirrorImpl(
            const prefix0.FlutterModelFormValidator(), 3, 25),
        r.ImplicitSetterMirrorImpl(
            const prefix0.FlutterModelFormValidator(), 3, 26),
        r.ImplicitGetterMirrorImpl(
            const prefix0.FlutterModelFormValidator(), 4, 27),
        r.ImplicitSetterMirrorImpl(
            const prefix0.FlutterModelFormValidator(), 4, 28),
        r.ImplicitGetterMirrorImpl(
            const prefix0.FlutterModelFormValidator(), 5, 29),
        r.ImplicitSetterMirrorImpl(
            const prefix0.FlutterModelFormValidator(), 5, 30),
        r.ImplicitGetterMirrorImpl(
            const prefix0.FlutterModelFormValidator(), 6, 31),
        r.ImplicitSetterMirrorImpl(
            const prefix0.FlutterModelFormValidator(), 6, 32),
        r.ImplicitGetterMirrorImpl(
            const prefix0.FlutterModelFormValidator(), 7, 33),
        r.ImplicitSetterMirrorImpl(
            const prefix0.FlutterModelFormValidator(), 7, 34),
        r.ImplicitGetterMirrorImpl(
            const prefix0.FlutterModelFormValidator(), 8, 35),
        r.ImplicitSetterMirrorImpl(
            const prefix0.FlutterModelFormValidator(), 8, 36),
        r.ImplicitGetterMirrorImpl(
            const prefix0.FlutterModelFormValidator(), 9, 37),
        r.ImplicitSetterMirrorImpl(
            const prefix0.FlutterModelFormValidator(), 9, 38),
        r.ImplicitGetterMirrorImpl(
            const prefix0.FlutterModelFormValidator(), 10, 39),
        r.ImplicitSetterMirrorImpl(
            const prefix0.FlutterModelFormValidator(), 10, 40),
        r.MethodMirrorImpl(r'toString', 131138, 3, -1, 21, 21, null,
            const <int>[], const prefix0.FlutterModelFormValidator(), const []),
        r.ImplicitGetterMirrorImpl(
            const prefix0.FlutterModelFormValidator(), 11, 42),
        r.MethodMirrorImpl(r'toString', 131138, 4, -1, 21, 21, null,
            const <int>[], const prefix0.FlutterModelFormValidator(), const []),
        r.ImplicitGetterMirrorImpl(
            const prefix0.FlutterModelFormValidator(), 12, 44)
      ],
      <m.ParameterMirror>[
        r.ParameterMirrorImpl(
            r'_reader',
            2130022,
            14,
            const prefix0.FlutterModelFormValidator(),
            -1,
            5,
            6,
            null,
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'_books',
            2130022,
            16,
            const prefix0.FlutterModelFormValidator(),
            -1,
            7,
            8,
            null,
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'other',
            32774,
            17,
            const prefix0.FlutterModelFormValidator(),
            -1,
            23,
            23,
            null,
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'invocation',
            32774,
            19,
            const prefix0.FlutterModelFormValidator(),
            -1,
            24,
            24,
            null,
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'property',
            32774,
            22,
            const prefix0.FlutterModelFormValidator(),
            -1,
            21,
            21,
            null,
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'_firstName',
            2130022,
            24,
            const prefix0.FlutterModelFormValidator(),
            -1,
            9,
            10,
            null,
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'_lastName',
            2130022,
            26,
            const prefix0.FlutterModelFormValidator(),
            -1,
            9,
            10,
            null,
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'_gender',
            2130022,
            28,
            const prefix0.FlutterModelFormValidator(),
            -1,
            11,
            12,
            null,
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'_birthDay',
            2130022,
            30,
            const prefix0.FlutterModelFormValidator(),
            -1,
            13,
            14,
            null,
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'_subscriptionDate',
            2130022,
            32,
            const prefix0.FlutterModelFormValidator(),
            -1,
            13,
            14,
            null,
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'_title',
            2130022,
            34,
            const prefix0.FlutterModelFormValidator(),
            -1,
            9,
            10,
            null,
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'_literaryGenres',
            2130022,
            36,
            const prefix0.FlutterModelFormValidator(),
            -1,
            15,
            16,
            null,
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'_releaseDate',
            2130022,
            38,
            const prefix0.FlutterModelFormValidator(),
            -1,
            13,
            14,
            null,
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'_price',
            2130022,
            40,
            const prefix0.FlutterModelFormValidator(),
            -1,
            17,
            18,
            null,
            const [],
            null,
            null)
      ],
      <Type>[
        prefix1.StepForm,
        prefix1.Reader,
        prefix1.Book,
        prefix1.EGender,
        prefix1.ELiteraryGenre,
        const m.TypeValue<prefix6.FormGroupElement<prefix1.Reader>>().type,
        prefix6.FormGroupElement,
        const m.TypeValue<prefix7.FormArrayElement<prefix1.Book>>().type,
        prefix7.FormArrayElement,
        const m.TypeValue<prefix8.FormControlElement<String>>().type,
        prefix8.FormControlElement,
        const m.TypeValue<prefix8.FormControlElement<prefix1.EGender>>().type,
        prefix8.FormControlElement,
        const m.TypeValue<prefix8.FormControlElement<DateTime>>().type,
        prefix8.FormControlElement,
        const m.TypeValue<
                prefix8.FormControlElement<List<prefix1.ELiteraryGenre>>>()
            .type,
        prefix8.FormControlElement,
        const m.TypeValue<prefix8.FormControlElement<num>>().type,
        prefix8.FormControlElement,
        int,
        bool,
        String,
        Type,
        Object,
        Invocation
      ],
      5,
      {
        r'==': (dynamic instance) => (x) => instance == x,
        r'toString': (dynamic instance) => instance.toString,
        r'noSuchMethod': (dynamic instance) => instance.noSuchMethod,
        r'hashCode': (dynamic instance) => instance.hashCode,
        r'runtimeType': (dynamic instance) => instance.runtimeType,
        r'getPropertyFullname': (dynamic instance) =>
            instance.getPropertyFullname,
        r'reader': (dynamic instance) => instance.reader,
        r'books': (dynamic instance) => instance.books,
        r'firstName': (dynamic instance) => instance.firstName,
        r'lastName': (dynamic instance) => instance.lastName,
        r'gender': (dynamic instance) => instance.gender,
        r'birthDay': (dynamic instance) => instance.birthDay,
        r'subscriptionDate': (dynamic instance) => instance.subscriptionDate,
        r'title': (dynamic instance) => instance.title,
        r'literaryGenres': (dynamic instance) => instance.literaryGenres,
        r'releaseDate': (dynamic instance) => instance.releaseDate,
        r'price': (dynamic instance) => instance.price,
        r'index': (dynamic instance) => instance.index
      },
      {
        r'reader=': (dynamic instance, value) => instance.reader = value,
        r'books=': (dynamic instance, value) => instance.books = value,
        r'firstName=': (dynamic instance, value) => instance.firstName = value,
        r'lastName=': (dynamic instance, value) => instance.lastName = value,
        r'gender=': (dynamic instance, value) => instance.gender = value,
        r'birthDay=': (dynamic instance, value) => instance.birthDay = value,
        r'subscriptionDate=': (dynamic instance, value) =>
            instance.subscriptionDate = value,
        r'title=': (dynamic instance, value) => instance.title = value,
        r'literaryGenres=': (dynamic instance, value) =>
            instance.literaryGenres = value,
        r'releaseDate=': (dynamic instance, value) =>
            instance.releaseDate = value,
        r'price=': (dynamic instance, value) => instance.price = value
      },
      <m.LibraryMirror>[
        r.LibraryMirrorImpl(
            r'example.models',
            Uri.parse(r'reflectable://0/example.models'),
            const prefix0.FlutterModelFormValidator(),
            const <int>[],
            {},
            {},
            const <Object>[prefix0.flutterModelFormValidator],
            null)
      ],
      [])
};

final _memberSymbolMap = null;

void initializeReflectable() {
  r.data = _data;
  r.memberSymbolMap = _memberSymbolMap;
}
